---
title: "Journal"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```
## Easy Practice Problems for Week 1
### Problem 1
Do simple math with numbers
```{r}

1+1
7-3
3*8
10/2

```
### Problem 2
Put numbers into variables-then do simple math
```{r}
AV<-3
C<-2
D<-4

AV+C
D-AV
C*D
D/C
```
###Problem 3
Place numbers 1-100 seperately 
```{r}
for(i in 1:100){
  print(i)
}
seq(1:100)
```
###Problem 4
Find sum of all intergers 1-100
```{r}
Vec<-(1:100)
sum(Vec)

```
###Problem 5
Summing using For Loop
```{r}
Numbers<-c()
Sum<-0
for (i in 1:100){
  if(i%%1==0){
    Numbers<-c(Numbers,i)
    Sum<-Sum+i
    
  }
}

 print(Sum) 
```
###Problem 6
Make your own summing function
```{r}
Sumfun<-function(a){
  total<-0
  for(i in a){
    total<-total+i
  }
return(total)
}

TestRun<-(1:3)
Sumfun(TestRun)


```

