---
title: "Statistics"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```
###Null Distributions
1) Sample from normal distribution

```{r}
Stat<-rnorm(100,0,1)
```
2) Get the mean differences
```{r}
null <- replicate(10000,mean(rnorm(10,0,1)-mean(rnorm(10,0,1))))                
```
3) Get alpha level relationships
```{r}
#directional positive
sorted_null <- sort(null)
sorted_null[9500]
#nondirectional
sorted_null <- sort(abs(null))
sorted_null[9500]
```
###T test
```{r}
t_dist <- replicate(10000,t.test(rnorm(10,0,1))$statistic)
ts <- c(.5,1,2,2.5)
sim_t <- c()
for(i in ts){
  sim_t <- c(sim_t,length(t_dist[t_dist >= i])/10000)
}
  
sim_t-(1-pt(ts,9))
```
###Correlation
```{r}
null <- replicate(10000,cor(rnorm(10,0,1),rnorm(10,0,1)))
sorted_null <- sort(abs(null))
sorted_null[9500]
null <- replicate(10000,cor(rnorm(100,0,1),rnorm(100,0,1)))
sorted_null <- sort(abs(null))
sorted_null[9500]
```

